repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: .k8s
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^(app/|tests/)
        exclude: ".*/migrations/.*"
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        include: ^(app/|tests/)
        exclude: ".*/migrations/.*"
        args:
          ["--profile=black", "--project=app/", "--section-default=THIRDPARTY"]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: ^(app/|tests/)
        exclude: ".*/migrations/.*"
