version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/opt/service
      - ./tests:/opt/service/tests
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  redis:
    image: bitnami/redis:6.2.7
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "7379:6379"
  celery_worker:
    build: .
    container_name: bakersoft-worker
    command: celery -A core.celery worker -E --loglevel=info
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  celery_beat:
    build: .
    container_name: bakersoft-beat
    command: celery -A core.celery beat --loglevel=info
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
