# Generated by Django 3.2 on 2022-09-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimelog',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='work_tracking.employee'),
            preserve_default=False,
        ),
    ]
