# Generated by Django 3.2 on 2022-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0002_alter_worktimelog_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktimelog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
