# Generated by Django 3.2 on 2022-09-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0003_auto_20220910_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktimelog',
            old_name='achievment',
            new_name='achievement',
        ),
    ]
