# Generated by Django 3.2 on 2022-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0005_auto_20220910_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(is_leader=True), fields=('team',), name='unique_team_leader'),
        ),
    ]
