# Generated by Django 3.2 on 2022-09-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0006_auto_20220910_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_team_leader',
        ),
    ]
