# Generated by Django 3.2 on 2022-09-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0007_auto_20220910_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='work_tracking.project'),
            preserve_default=False,
        ),
    ]
