# Generated by Django 3.2 on 2022-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0008_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
