# Generated by Django 3.2 on 2022-09-11 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0010_taskstatechange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatechange',
            options={},
        ),
        migrations.RemoveField(
            model_name='taskstatechange',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskstatechange',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='taskstatechange',
            name='transitioned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
